[build]
  command = "npm install"
  publish = "src/public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["node_modules/sql.js/dist/sql-wasm.wasm"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200
  force = true
